### ISSUE TITLE
ZipException: error in opening zip file in default-cluster-app

### ISSUE THREAD

**Issue by mbastian** [mojohaus/nbm-maven-plugin#15]
Hi, we're running into the following exception when building from certain Windows machines. The build works fine on Mac OS X, Linux and some Windows although we don't know the root cause. 

This is the environment

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files (x86)\apache-maven-3.3.9\bin\..
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

```
[ERROR] Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.14:cluster-app (default-cluster-app) on project gephi: Cannot process etc folder content creation. error in opening zip file -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.14:cluster-app (default-cluster-app) on project gephi: Cannot process etc folder content creation.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot process etc folder content creation.
    at org.codehaus.mojo.nbm.CreateClusterAppMojo.execute(CreateClusterAppMojo.java:615)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)
    at java.util.zip.ZipFile.<init>(ZipFile.java:163)
    at org.codehaus.mojo.nbm.CreateClusterAppMojo.createBinEtcDir(CreateClusterAppMojo.java:796)
    at org.codehaus.mojo.nbm.CreateClusterAppMojo.execute(CreateClusterAppMojo.java:611)
    ... 22 more
```

Complete log can be found here: https://gist.github.com/jacomyma/793f9599763f7e9fd8d8

Any idea what the problem is? Maybe some permissions error? Anything we can help you with to reproduce the error? Thanks!

**Comment by ebarboni** [comment]
Hi, as a first step I would suggest to try to upgrade the nbm version of the plugin to 4.1 as it may contains some fix to work with release 81.

**Comment by mbastian** [comment]
Ok, I tried with version 4.1 and the error remains the same.

**Comment by mkleint** [comment]
it's either us (the plugin) not closing some streams or some other application taking hold of it I believe

**Comment by mkleint** [comment]
what version of maven are you using? It seem like we first try to download a version of a nbm file containing some files of interest and then we try to extract those files.

including "org.netbeans.modules:org-netbeans-modules-apisupport-harness:<VERSION>:nbm-file" as part of the application dependencies could be a workaround..

**Comment by mbastian** [comment]
Version of Maven is 3.3.9.

I tried the workaround by adding the following to the dependencies of the nbm-application module and it unfortunately didn't fix it.

```
<dependency>
          <groupId>org.netbeans.modules</groupId>
          <artifactId>org-netbeans-modules-apisupport-harness</artifactId>
          <version>RELEASE81</version>
          <type>nbm-file</type>
</dependency>
```

**Comment by ebarboni** [comment]
I try on my windows 10 no luck to reproduce.
Maybe the tool Process Explorer at https://technet.microsoft.com/en-us/sysinternals/bb896653 may help to know wich process is locking.
